name: Docker Meta Publish

description: Creates and pushes Docker manifests with metadata to ECR

inputs:
  aws_region:
    required: false
    description: AWS Region
    default: ap-southeast-1
  ecr_uri:
    required: true
    description: ECR URI to push image to
  ecr_registries:
    required: true
    description: AWS account IDs included with ECR login (comma separated)
  docker_meta_tags:
    required: true
    description: Tags argument to docker meta
  amend_tags:
    required: true
    description: Image tags to be linked in Docker manifest
  role_to_assume:
    required: true
    description: ARN of the role that is authorized to publish the image
  buildx_image_uri:
    required: false
    description: Optionally override buildx image
    default: "moby/buildkit:master"

outputs:
  tags:
    description: Image tags of the manifest
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: "true"
        registries: ${{ inputs.ecr_registries }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=${{ inputs.buildx_image_uri }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.ecr_uri }}
        tags: ${{ inputs.docker_meta_tags }}

    - name: Docker Manifest Create
      shell: bash
      run: |
        # Create manifest list
        docker buildx imagetools create -t ${{ inputs.ecr_uri }}:${{ steps.meta.outputs.version }} ${{ inputs.amend_tags }}
        
        # Push the manifest
        docker buildx imagetools push ${{ inputs.ecr_uri }}:${{ steps.meta.outputs.version }}
