name: ECR Tag Validation

on:
  workflow_call:
    inputs:
      aws_region:
        required: false
        type: string
        description: AWS Region
        default: ap-southeast-1
      image_tag:
        required: false
        type: string
        description: The image/artifact tag that is to be validated
      image_tags:
        required: false
        type: string
        description: The image/artifact tags to be validated, space separated
      registry:
        required: true
        type: string
        description: AWS account ID used for ECR login
      repo_name:
        required: true
        type: string
        description: Short name of the ECR repository
      role_to_assume:
        required: true
        type: string
        description: AWS IAM role to assume to perform ECR query

jobs:
  ecr-tag-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ inputs.registry }}

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Validate artifact existence
        if: ${{ inputs.image_tag != '' }}
        shell: bash
        run: |
          aws ecr describe-images --repository-name=${{ inputs.repo_name }} --registry-id=${{ inputs.registry }} --image-ids=imageTag=${{ inputs.image_tag }}
          if [[ $? == 0 ]]; then
            echo "Tag exists"
          else
            echo "Tag does not exist"
            exit 1
          fi

      - name: Validate artifacts existence
        if: ${{ inputs.image_tags != '' }}
        shell: bash
        run: |
          for tag in ${{ inputs.image_tags }};
          do
            aws ecr describe-images --repository-name=${{ inputs.repo_name }} --registry-id=${{ inputs.registry }} --image-ids=imageTag=$tag
            if [[ $? == 0 ]]; then
              echo "Tag exists"
            else
              echo "Tag does not exist"
              exit 1
            fi
          done